# app/helpers/customer_helper.rb
module CustomerHelper
  CUSTOMERS = [
    "3B Hungária Kft., Zalaegerszeg",
    "ALREC-TEC GmbH, Mömbris",
    "bage plastics Deutschland GmbH",
    "BAGE Plastics GmbH, St.Marien",
    "BMCR, Italy",
    "Bollegraaf Recycling Machinery bv, Appingedam",
    "BT-Systems GmbH",
    "COLEO RECYCLING BCN, S.L., MATARÓ",
    "Daio Engineering Co., Ltd., JP",
    "Dirk Lichtblau e.K., Dresden",
    "DXG Ltd., Gwangju-Si, Gyeonggi-Do",
    "EAGLE VIZION, Sherbrooke, QC, CA",
    "Enva Plastics Limited",
    "Forschungsstiftung der Papierindustrie, Heidenau",
    "Fraunhofer IWKS, Alzenau",
    "greateyes GmbH, Berlin",
    "Green Mind Recycling",
    "GS GmbH",
    "IONIAENT CO., LTD",
    "KrownCORP",
    "Laboratoire Laboragro, LA GRANDE PAROISSE",
    "Lubo Systems bv, Emmen",
    "LUGO Machinery & Innovation Ltd., IL",
    "M & Tech Co., Ltd, KR",
    "Matvision SRL",
    "MBA Polymers UK Ltd, Warrington, UK",
    "MGG Polymers Austria",
    "Military University of Technology",
    "Nantong Wealth Machinery Technical CO.,LTD.",
    "NC STATE UNIVERSITY, Raleigh, NC, US",
    "Neolithics, Tel Aviv – Yaffo",
    "NewRetex A/S",
    "O2 Enviroment Technology, KR",
    "Picvisa Machine Vision Systems, SL, Barcelona",
    "Polytec France SAS, Châtillon",
    "PRS - Services, Poland",
    "PRS Services, Schönberg",
    "PTS – Institut für Fasern & Papier gGmbH",
    "PTSV GmbH, Heidenau",
    "Recover Pure Materials GmbH, Pforzheim",
    "Senro B.V., Hengelo",
    "Sesotec GmbH",
    "SGM Magnetics S.p.A.",
    "Shandong Jiekong Information Technology Co., Ltd.",
    "Sherbrooke O.E.M. Ltd, Sherbrooke (Qc), CA",
    "Skyplast IKE, Megara",
    "SOEX Textil-Vermarktungsgesellschaft m.b.H., Ahren",
    "Stemmer Imaging AG",
    "Stemmer Imaging AG",
    "Textilforschungsinstitut Thüringen-Vogtland e. V.",
    "Thorey Gera Textilveredelung GmbH, Gera",
    "Toratecnica S. L., Igualada (BCN)",
    "Université de Liège",
    "VALVAN, Menen",
    "VOIGT SALUS. Rechtsanwälte und Steuerberater",
    "Wastex Technologies S.L."
  ].freeze
end